### PR TITLE
Partial iphone10,6 support

### PR DESCRIPTION
**Pull request by lretq**
Added iphone10,6 in main.c
Problem: muteswitch is not getting found

### CODE REVIEW

**Comment by legendary-cookie** [comment]
I also noticed something strange: when muting the phone while you should press the homebutton, it finds an address, is that normal?

**Comment by pixelomer** [comment]
To the button helper, there is no difference between any of the buttons/switches. If you hold the power button when it asks you to mute the device, it will gladly print the power button address as the mute switch address. The labels are only there to make it easier to identify which address is for which button after you're done.

**Comment by pixelomer** [comment]
Please add the mute switch address as well to your pull request. What you said earlier means the button helper is able to find the mute switch address. It's possible that it just didn't work the first time.

> I also noticed something strange: when muting the phone while you should press the homebutton, it finds an address, is that normal?

**Comment by legendary-cookie** [comment]
Tried multiple times already, maybe lies out of the range?

**Comment by pixelomer** [comment]
Just to make sure, you unmute the device when it asks you to release the mute switch right? Also what you said doesn't make sense. The code that finds the home button address is the same as the code that finds the mute switch address.

**Comment by legendary-cookie** [comment]
Yes I unmute... And yes it doesn't make sense thats what I mean. I have tried it multiple times, always with the same results, and also the mute thing occurred multiple times?

**Pull request closed without merging**
